-- MySQL Script generated by MySQL Workbench
-- qua 22 nov 2023 12:29:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema socialmedia_api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema socialmedia_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `socialmedia_api` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `socialmedia_api` ;

-- -----------------------------------------------------
-- Table `socialmedia_api`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia_api`.`users` (
  `id_users` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `cpf` VARCHAR(25) NOT NULL,
  `date_birth` DATE NOT NULL,
  `email` VARCHAR(25) NULL DEFAULT NULL,
  `password` VARCHAR(35) NULL DEFAULT NULL,
  PRIMARY KEY (`id_users`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `socialmedia_api`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia_api`.`chats` (
  `id_chats` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_sender` INT(11) NOT NULL,
  `fk_receiver` INT(11) NOT NULL,
  `chat_text` VARCHAR(255) NULL DEFAULT NULL,
  `chat_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_chats`),
  INDEX `fk_sender` (`fk_sender` ASC) VISIBLE,
  INDEX `fk_receiver` (`fk_receiver` ASC) VISIBLE,
  CONSTRAINT `chats_ibfk_1`
    FOREIGN KEY (`fk_sender`)
    REFERENCES `socialmedia_api`.`users` (`id_users`),
  CONSTRAINT `chats_ibfk_2`
    FOREIGN KEY (`fk_receiver`)
    REFERENCES `socialmedia_api`.`users` (`id_users`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `socialmedia_api`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia_api`.`posts` (
  `id_posts` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_user` INT(11) NOT NULL,
  `text_posts` VARCHAR(255) NULL DEFAULT NULL,
  `time_posts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `likes_count` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`id_posts`),
  INDEX `fk_user` (`fk_user` ASC) VISIBLE,
  CONSTRAINT `posts_ibfk_1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `socialmedia_api`.`users` (`id_users`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `socialmedia_api`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia_api`.`comments` (
  `id_comments` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_user` INT(11) NOT NULL,
  `fk_post` INT(11) NOT NULL,
  `comment_text` VARCHAR(255) NULL DEFAULT NULL,
  `comment_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_comments`),
  INDEX `fk_user` (`fk_user` ASC) VISIBLE,
  INDEX `fk_post` (`fk_post` ASC) VISIBLE,
  CONSTRAINT `comments_ibfk_1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `socialmedia_api`.`users` (`id_users`),
  CONSTRAINT `comments_ibfk_2`
    FOREIGN KEY (`fk_post`)
    REFERENCES `socialmedia_api`.`posts` (`id_posts`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `socialmedia_api`.`connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia_api`.`connections` (
  `id_connections` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_user` INT(11) NOT NULL,
  `fk_friend` INT(11) NOT NULL,
  `connection_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_connections`),
  INDEX `fk_user` (`fk_user` ASC) VISIBLE,
  INDEX `fk_friend` (`fk_friend` ASC) VISIBLE,
  CONSTRAINT `connections_ibfk_1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `socialmedia_api`.`users` (`id_users`),
  CONSTRAINT `connections_ibfk_2`
    FOREIGN KEY (`fk_friend`)
    REFERENCES `socialmedia_api`.`users` (`id_users`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `socialmedia_api`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `socialmedia_api`.`likes` (
  `id_likes` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_post` INT(11) NOT NULL,
  `fk_user` INT(11) NOT NULL,
  `like_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_likes`),
  INDEX `fk_post` (`fk_post` ASC) VISIBLE,
  INDEX `fk_user` (`fk_user` ASC) VISIBLE,
  CONSTRAINT `likes_ibfk_1`
    FOREIGN KEY (`fk_post`)
    REFERENCES `socialmedia_api`.`posts` (`id_posts`),
  CONSTRAINT `likes_ibfk_2`
    FOREIGN KEY (`fk_user`)
    REFERENCES `socialmedia_api`.`users` (`id_users`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `socialmedia_api`;

DELIMITER $$
USE `socialmedia_api`$$
CREATE
DEFINER=`leonardo`@`localhost`
TRIGGER `socialmedia_api`.`increment_like_count`
AFTER INSERT ON `socialmedia_api`.`likes`
FOR EACH ROW
BEGIN
    UPDATE posts
    SET likes_count = likes_count + 1
    WHERE id_posts = NEW.fk_post;
END$$

USE `socialmedia_api`$$
CREATE
DEFINER=`leonardo`@`localhost`
TRIGGER `socialmedia_api`.`prevent_duplicate_likes`
BEFORE INSERT ON `socialmedia_api`.`likes`
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1
        FROM likes
        WHERE fk_post = NEW.fk_post AND fk_user = NEW.fk_user
    ) THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Não é permitido dar mais de um like no mesmo post.';
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
